/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Airship.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Airship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Airship.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/Airship.glb')
