/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ship.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ship.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Airship.geometry} material={materials.Mat} />
      <mesh geometry={nodes.Helix.geometry} material={materials.Mat} position={[-0.205, 29.083, -87.561]} />
      <mesh geometry={nodes.helix1.geometry} material={materials.Mat} position={[25.16, 32.132, 37.71]} rotation={[Math.PI, -0.226, Math.PI]} />
      <mesh geometry={nodes.helix2.geometry} material={materials.Mat} position={[-25.16, 32.132, 37.71]} rotation={[0, -0.2, 0]} />
    </group>
  )
}

useGLTF.preload('/ship.glb')
