/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/ship.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Plane(props) {
  const { nodes, materials } = useGLTF('./models/Ship.glb')

  const HELIX_SPEED=6;
  const helix =useRef();
  const helix1 =useRef();
  const helix2 =useRef();
  useFrame((_state,delta)=>{
    helix.current.rotation.z += delta* HELIX_SPEED;
  })
  useFrame((_state,delta)=>{
    helix1.current.rotation.y += delta* HELIX_SPEED;
  })
  useFrame((_state,delta)=>{
    helix2.current.rotation.y += delta* HELIX_SPEED;
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Airship.geometry} material={materials.Mat} ><meshStandardMaterial color="white" /></mesh>
      <mesh ref={helix} geometry={nodes.Helix.geometry} material={materials.Mat} position={[-0.205, 29.083, -87.561]}><meshStandardMaterial color="white" /></mesh>
      <mesh ref={helix1} geometry={nodes.helix1.geometry} material={materials.Mat} position={[25.16, 32.132, 37.71]} rotation={[Math.PI, -0.226, Math.PI]}><meshStandardMaterial color="white" /></mesh>
      <mesh ref={helix2} geometry={nodes.helix2.geometry} material={materials.Mat} position={[-25.16, 32.132, 37.71]} rotation={[0, -0.2, 0]} ><meshStandardMaterial color="white" /></mesh>
    </group>
  )
}

useGLTF.preload('./models/Ship.glb')
